// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_UIdSsPBWR7fLTo-hopWHlP436-4lQAc',
    appId: '1:968274459759:web:a58e2b93c0cd5a04a4a19a',
    messagingSenderId: '968274459759',
    projectId: 'flash-chat-6b5d9',
    authDomain: 'flash-chat-6b5d9.firebaseapp.com',
    storageBucket: 'flash-chat-6b5d9.appspot.com',
    measurementId: 'G-3KMJ1CJFX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGttblcjkCgQIgB6envvSPbwb7Oif9qDI',
    appId: '1:968274459759:android:1bf471d440ac4252a4a19a',
    messagingSenderId: '968274459759',
    projectId: 'flash-chat-6b5d9',
    storageBucket: 'flash-chat-6b5d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_jpg2PznOD0gfsanFn-JOnoc9CZJIHNw',
    appId: '1:968274459759:ios:671816c9fc5589b8a4a19a',
    messagingSenderId: '968274459759',
    projectId: 'flash-chat-6b5d9',
    storageBucket: 'flash-chat-6b5d9.appspot.com',
    iosClientId: '968274459759-rdmopvgmuru93ld2u5h7e7mhqg2u0ht8.apps.googleusercontent.com',
    iosBundleId: 'co.appbrewery.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_jpg2PznOD0gfsanFn-JOnoc9CZJIHNw',
    appId: '1:968274459759:ios:ac22cb30c9c53dbca4a19a',
    messagingSenderId: '968274459759',
    projectId: 'flash-chat-6b5d9',
    storageBucket: 'flash-chat-6b5d9.appspot.com',
    iosClientId: '968274459759-eq3anrtotiuskspd8r46fareppjboqh7.apps.googleusercontent.com',
    iosBundleId: 'co.appbrewery.flashChatFlutter',
  );
}
